evo_test/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', RedirectView.as_view(permanent=False, url="/items/")),
    path('items/', include('items.urls', namespace='items')),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

items/urls.py
from django.urls import path
from .views import AllItemsList, FridgeList, TVList, clickCount

app_name = 'items'

urlpatterns = [
    path("", AllItemsList.as_view(), name="items-list"),
    path("fridges", FridgeList.as_view(), name="fridge-list"),
    path("tv-sets", TVList.as_view(), name="tv-list"),
    path("click-count/", clickCount, name='click-item')
]

items/models.py
from django.db import models


class Manufacturer(models.Model):
    name = models.CharField(max_length=68)

    def __str__(self):
        return self.name


# class AbstractItem(models.Model):
#     name = models.CharField(max_length=48)
#     manufacturer = models.ForeignKey('Manufacturer', on_delete=models.SET_NULL)
#     description = models.TextField(max_length=500, help_text='Enter a description of an item')
#     image = models.ForeignKey('ItemImage', on_delete=models.SET_NULL)
#     number_of_clicks = models.PositiveIntegerField(default=0)


class Category(models.Model):
    """
    Model representing an item category (e.g. Fridge, TV).
    """
    category = models.CharField(max_length=15)

    class Meta:
        verbose_name_plural = 'categories'

    def __str__(self):
        return self.category


class Item(models.Model):
    name = models.CharField(max_length=48, default='Item')
    category = models.ForeignKey('Category', on_delete=models.SET_NULL, null=True)
    manufacturer = models.ForeignKey('Manufacturer', on_delete=models.SET_NULL, null=True)
    item_image = models.ForeignKey('ItemImage', on_delete=models.SET_NULL, null=True, blank=True)
    description = models.TextField(max_length=500, help_text='Enter a description of an item', blank=True, null=True)
    number_of_clicks = models.PositiveIntegerField(default=0)

    def __str__(self):
        return "{} by {}".format(self.category, self.manufacturer)

    # def add_click(self):
    #     self.number_of_clicks += 1

    class Meta:
        ordering = ["-number_of_clicks"]


class ItemImage(models.Model):
    image = models.ImageField(upload_to='items_images/')
    image_category = models.ForeignKey('Category', on_delete=models.SET_NULL, null=True)

    def __str__(self):
        return "Photo of a {} #{}".format(self.image_category, self.id)

items/views.py
from django.shortcuts import HttpResponse
from django.views.generic import ListView
from .models import Item
from django.db.models import F
from django.core import serializers


# Create your views here.
class AllItemsList(ListView):
    model = Item
    context_object_name = 'items'
    queryset = Item.objects.all()
    template_name = 'items/items.html'


class FridgeList(ListView):
    model = Item
    context_object_name = 'items'
    queryset = Item.objects.filter(category__category='Fridge')
    template_name = 'items/fridge_list.html'


class TVList(ListView):
    model = Item
    context_object_name = 'items'
    queryset = Item.objects.filter(category__category='TV Set')
    template_name = 'items/tv_list.html'


def clickCount(request):
    item_id = None
    if request.method == "GET":
        item_id = request.GET['item_id']

    item = Item.objects.get(id=item_id)
    if item:
        clicks = item.number_of_clicks + 1
        item.number_of_clicks = clicks
        item.save()

    return HttpResponse(clicks)

items/templates/items/fridge_list.html
{% extends "base.html" %}
{% load static %}

{% block title %}Fridges{% endblock %}

{% block content %}
  {% for item in items %}
    {% include 'items/item_view.html' %}
  {% endfor %}
{% endblock %}

items/templates/items/item_view.html
{% load static %}
  <div class="row align-items-center click-container" style="padding-bottom: 10px;" data-item-id="{{ item.id }}">
    <div class="col-6 mx-auto text-center item-div">
      <div class="image-div">
        <img src="{{ item.item_image.image.url }}" class="img-responsive" alt='Image of an Item'>
      </div>

      <h4>{{ item.category.category }} {{ item.name }}</h4>
      <p>
          {{ item.description|truncatechars_html:70 }}
      </p>
      <h4>Number of clicks:</h4>
      <p class="clicks-number">{{ item.number_of_clicks }}</p>
    </div>

</div>

items/templates/items/items.html
{% extends "base.html" %}
{% load staticfiles %}

{% block title %}All Items{% endblock %}

{% block content %}


  {% for item in items %}
    {% include 'items/item_view.html' %}
  {% endfor %}

{% endblock %}

items/templates/items/tv_list.html
{% extends "base.html" %}

{% block title %}TV Sets{% endblock %}

{% block content %}
  {% for item in items %}
    {% include 'items/item_view.html' %}
  {% endfor %}
{% endblock %}

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>{% block title %}{% endblock %}</title>
    <!-- Bootstrap -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <!-- Roboto Font -->
    <link href="https://fonts.googleapis.com/css?family=Roboto:100,400,500" rel="stylesheet">
    <!-- Custom style -->
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
  </head>
  <body>

    <div class="container h-100">


      {% include 'nav.html' %}

    <div class="main justify-content-center">
      {% block content %}
      {% endblock content %}
    </div>

    </div>

    <!-- <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script> -->

    <!-- <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script> -->
    <script type="text/javascript" src="{% static 'js/jquery.js' %}"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script type="text/javascript" src="{% static 'js/script.js' %}"></script>
  </body>
</html>

templates/nav.html
<nav class="navbar navbar-expand-lg navbar-light bg-light justify-content-center"
  <ul class="nav justify-content-center">
    <li class="nav-item">
      <a class="nav-link" href="{% url 'items:items-list' %}">All Items</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="{% url 'items:fridge-list' %}">Fridges</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="{% url 'items:tv-list' %}">TV Sets</a>
    </li>
  </ul>
</nav>